name: build

on: [push, pull_request]

jobs:
  build:
    name: Build Next App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        run: |
          yarn lint
          yarn build
